---
# tasks file for 0-1universe
- name: Namespace for 0-1universe
  community.kubernetes.k8s:
    state: "{{ universe_state }}"
    name: "{{ universe_namespace }}"
    api_version: v1
    kind: Namespace

- name: 0-1universe service
  community.kubernetes.k8s:
    state: "{{ universe_state }}"
    namespace: "{{ universe_namespace }}"
    template: "{{ item }}"
  with_items:
    - cea.yml.j2
    - tee.yml.j2
    - ingress.yml.j2
  tags:
    - 0-1universe
